#+TITLE: Skills, Tactics, Plays - Intro
#+AUTHOR: Jay Kamat
#+EMAIL: jaygkamat@gmail.com

# Export section for md
* Skills, Tactics, Plays {#t20172}                                 :docs:
* Python Overview
** Using Python
#+BEGIN_SRC shell
  $ python3
  Python 3.5.3 (default, Jan 19 2017, 14:11:04)
  [GCC 6.3.0 20170118] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> print("Hello RoboCup!")
  Hello RoboCup!
#+END_SRC
** Basic Syntax
#+BEGIN_SRC python :exports both :results output :cache yes
  # Hello world
  print("Hello World!")

  # Set a variable
  myinteger = 1
  mydouble = 1.0
  mystr = "one"

  print(myinteger)
  print(mydouble)
  print(mystr)
#+END_SRC

#+RESULTS[e489be2aa6424fd489bf44e6633bdeefe5bebcac]:
: Hello World!
: 1
: 1.0
: one
** IF Statements and Conditionals
#+BEGIN_SRC python :exports both :results output :cache yes
  if True:
      print("RoboCup is great!")
  if False:
      print("IGVC is great...")

  if True:
      print("RoboCup is the best!")
  elif True:
      print("RoboRacing is the best...")
  else:
      print("IGVC is the best...")

  a = 5
  if a > 2:
      print("a is greater than 2!")
  if a > 2 and a < 10:
      print("a is > 2 and < 10")
  print("a is greater than 3" if a > 3 else "a is less than 3")
  print("a is greater than 9" if a > 9 else "a is less than 9")
#+END_SRC

#+RESULTS[bd799ab625a59ed63cb49f882591e36520f1f803]:
: RoboCup is the Best!
: RoboCup is Great!
: a is greater than 2!
: a is > 2 and < 10
: a is greater than 3
: a is less than 9

** Loops and range()
#+BEGIN_SRC python :exports both :results output :cache yes
  a = 10
  while a > 0:
      print(a, end=" ")
      a = a - 1
  print("")

  print(list(range(10)))
  for i in range(10):
      print(i * i, end=" ")
  print("")
#+END_SRC
** Functions
#+BEGIN_SRC python :exports both :results output :cache yes
  def func1(a, b):
      return a + b

  print(func1(2, 4))

  # Lambda Expressions ('advanced' topic)
  def secret_func():
      return "RoboCup!"
  def welcome(target):
      return "Welcome to " + target()

  print(welcome(secret_func))
  print(welcome(lambda: "RoboJackets!"))
  # Lambda with arguments
  # print(welcome(lambda arg1, arg2: "RoboJackets!"))
#+END_SRC

#+RESULTS[a218e7c68935997484fc27aef176998c92a2de9a]:
: 6
: Welcome to RoboCup!
: Welcome to RoboJackets!

** Object Oriented Python
#+BEGIN_SRC python :exports both :results output :cache yes
  class BaseClass():
      globalVar = 1
      # Constructor
      def __init__(self):
          print("Initializing a Base")
          self.local_var = 2

  class ChildClass(BaseClass):
      def __init__(self):
          super().__init__() # call superclass constructor
          print("Initializing Child")
          print("Our local var is: " + str(self.local_var))

  # When defining class methods, pass 'self' as the first arg.
  # Self refers to the current class instance.
  a = BaseClass()
  print("---")
  a = ChildClass()
#+END_SRC

#+RESULTS[aa87c5fe22ac017cb1320e3c85d8277e6259e135]:
: Initializing a Base
: ---
: Initializing a Base
: Initializing Child
: Our local var is: 2

** We can't teach a full year of programming in one hour. 
- Take advantage of resources like [[https://www.codecademy.com/][codeacademy]] or [[https://www.lynda.com/]lynda](to which you have access using your Georgia Tech information.)
- Programming is a language, and like every language, it takes time to become familiar with the syntax and vocabulary. 

** Additional Python Resources                                         :docs:
- [[http://lightbot.com/hocflash.html][lightbot]] - A Introduction to Programming Logic
- [[https://wiki.python.org/moin/BeginnersGuide/NonProgrammers][Python Beginner Hub]]
- [[https://learnxinyminutes.com/docs/python/][Python Syntax Overview]]
- [[http://thepythonguru.com/][A intro to python]]

* Plays, Tactics, Skills
- A Basic Unit in our AI
- Only one *Play* can run at a time
- A *play* may utilize multiple *tactics*, which themselves may utilize multiple *skills*. 
** Skill
- Involves only /one/ robot
- Extremely basic building blocks
- Examples
  - Move
  - Kick
  - Face a direction
  - Capture the ball
- Located in =soccer/gameplay/skills/=
** Tactics
- Involves multiple robots
- Utilize skills
- Can contain unique behavior (but usually not)
- Examples
  - Pass
  - Defend
  - Line Up
- Located in =soccer/gameplay/tactics/=
** Plays
- Only one can run
- Utilize tactics
- Examples
  - Basic122 (basic offense)
  - Two side attack (basic offense)
  - Stopped Play
  - Line Up
  - Corner Kick
- Located in =soccer/gameplay/plays/*/=
*** Notes                                                            :docs:
- Only plays are actually runnable in our model
  - If you want to run a tactic, make a dummy play that runs that tactic on startup
- For now, we'll only look at plays to keep things simple (maybe we'll get more complex later)

* Goals
- Understand how to use skills 
- Understand which points correspond to different locations on the field

** Assignments
- Make a robot move to all of the locations marked by a red dot
- Make a robot capture a ball
- Make a robot shoot on their goal using a line kick
- Make a robot shoot on their goal using a pivot kick

** Extension
- Put something here

** Tips
- The field coordinates start at 0, 0; Which is our Goal.
- Field Size Docs: ([[http://bit.ly/2cLsUBL][http://bit.ly/2cLsUBL]])
- Ball Position Docs: ([[http://bit.ly/2damxXA][http://bit.ly/2damxXA]])
- Move the template starter from ~soccer/gameplay/plays/skel/which_half.py~ to ~soccer/gameplay/plays/testing~
- Start by just printing the Y coordinate of the ball and work up from there
** Exercise Details                                                   :docs:
- Ask on [[https://github.com/RoboJackets/robocup-software/blob/master/soccer/gameplay/plays/skel/which_half.py][gitter]] for help and answers!
